{
	'name':'Inventory Reports, Stock Reports, Stock Turnover, Inventory Valuation and many more reports',
    'version': '17.0.0.0.1',
    'description': "Inventory Reports module for Stock / Inventory Turnover Ratio,Inventory Valuation,Stock Expiry / Expired,Stock Aging (Non-Moving),Stock / Inventory Coverage,	Stock Movement,Inventory Overstock Report,XYZ Analysis,ABC Analysis,Product Movement, Stock Availability,Balance Sheet,Stock Forecast,Reorder Analysis,Sales Analysis,LIFO stock, FIFO stock, Stock Reorder Analysis,Product Profitability Report stock in out report",
    'summary':'Generate Inventory Reports,Stock Reports, Inventory Turnover Report,Inventory Valuation,Stock Expired Report,Stock Aging,Stock / Inventory Coverage Stock Movement Inventory Overstock Report,XYZ Analysis ABC Analysis Product Movement Stock Availability,Balance Sheet,Stock Forecast Reorder Analysis Sales Analysis LIFO stock FIFO stock Reorder Analysis,Product Profitability Report  stock in out report',
	'depends': ['base','stock','sale','product','product_expiry','account','web'],
	'data': [
        'security/ir.model.access.csv',
        'views/client_action.xml',
		'views/inventory_turnover_view.xml',
		'views/fsn_moving_view.xml',
		# 'views/fsn_moving_graph.xml',
		'views/stock_availability.xml',
		'views/stock_movement_axis.xml',		
		'views/inventory_valuation.xml',
		'views/inventory_valuation_report_views.xml',
		'views/sales_analysis.xml',
		'views/stock_aging.xml',
		'views/reorder_analysis.xml',
		'views/stock_expiry.xml',
		'views/stock_expiry.xml',
		'views/stock_forecast.xml',
		'views/balance_sheet.xml',
		'views/inv_overstock.xml',
		'views/inventory_coverage.xml',
		'views/product_profitability.xml',
		'views/inventory_xyz_analysis.xml',
		'views/inventory_abc_analysis.xml',
		'views/inv_stock_alert.xml',
		'views/fifo_valuation.xml',
		'views/lifo_valuation.xml',
		'views/serial_tracking_report.xml',
		'views/stock_return.xml',
		'views/cost_analysis_location.xml',
		'views/stock_velocity.xml',
		'views/product_stock_in_out_by_month_views.xml',
		'report/inv_abc_analysis_pdf.xml',
		'report/inv_valuation_pdf.xml',
		'report/stock_in_out_report.xml',
		'report/stock_aging_pdf.xml',
		'report/reorder_analysis_pdf.xml',
		'report/stock_forecast_pdf.xml',
		'report/inv_overstock_pdf.xml',
		'report/fsn_moving_pdf.xml',
		'report/prod_profitability_pdf.xml',
		'report/stock_availability_pdf.xml',
		'report/stock_movement_pdf.xml',
		'report/sales_analysis_pdf.xml',
		'report/balance_sheet_pdf.xml',
		'report/inv_coverage_pdf.xml',
		'report/inv_xyz_analysis_pdf.xml',
		'report/inv_stock_alert_pdf.xml',
		'report/fifo_valuation_pdf.xml',
		'report/lifo_valuation_pdf.xml',
		'report/inv_turnover_pdf.xml',
		'report/stock_expiry_pdf.xml',
		'report/serial_tracking_pdf.xml',
		'report/cost_analysis_location_pdf.xml',
		'report/stock_return_pdf.xml',
		'report/stock_velocity_pdf.xml',
	    ],
	'assets': {
        'web.assets_backend': [
            # 'inventory_reports_adv_axis/static/src/js/*',
            # 'inventory_reports_adv_axis/static/src/xml/*',
            'inventory_reports_adv_axis/static/src/css/style.css',
        ]
    },
    'routes': [
            '/inventory_reports_adv_axis/download',
        ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'OPL-1',
    'price': 284,
    'currency': 'USD',
    'support': 'business@axistechnolabs.com',
    'author': 'Axis Technolabs',
    'website': 'https://www.axistechnolabs.com',
    'images': ['static/description/Stock_Inventory_reports.gif'],
}
