{
    'name': "mandob sales order",
    "version": "1.0",
    'summary': """editing""",
    'description': '''editing''',
    'sequence': 1,
    'category': 'Sale',
    "author" : "DOTSPRIME",
    "email": 'n4ajwa4@gmail.com',
    "license": 'OPL-1',
    "price": 25,
    "currency": "EUR",
    'depends': ['sale','base','customer_route_management','stock'],
    'data': ['views/editing.xml'],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
