from . import hr_employee
from . import ks_dashboard
from . import weekly_routs
from . import weekly_routs_line
from . import daily_visit
from . import route_line
from . import res_partner
from . import sale_order
from . import daily_visit_report
from . import account_move
from . import daily_realtime_report
from . import partner_visit_adjutment
